### PR TITLE
Kdenlive metadata to support animation.

### PR DESCRIPTION
**Pull request by SpacemanPaul**
"documentation" is here:

https://invent.kde.org/multimedia/kdenlive/-/blob/7836478b62a184d840dee2d37a28e263212d91e2/data/effects/README

but you're better off looking at the metadata for the standard frei0r plugins: https://invent.kde.org/multimedia/kdenlive/-/tree/7836478b62a184d840dee2d37a28e263212d91e2/data/effects

Note in particular that frei0r plugins seem to need the "animated" parameter type to achieve automation, which is not documented. 🙄

### CODE REVIEW

**Comment by gbendy** [comment]
Please remove the `.swp` file.

**Review by gbendy — CHANGES_REQUESTED** [review]
please remove the .swp file

**Comment by SpacemanPaul** [comment]
No wukkas.  Want me to add a .gitignore file too?  ;)

**Comment by gbendy** [comment]
> 
> 
> No wukkas. Want me to add a .gitignore file too? ;)

Would prefer you exited your editor before committing if it's the type that leaves files in the local directory. And added individual files rather than whole directories to ensure the cleanliness of the repository. :)

**Review by gbendy — APPROVED** [review]
Much less crud lying around now!

**Pull request merged**
